model:
  _convert_: all
  img_size:
  - 32
  - 128
  max_label_length: 25
  charset_train: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
  charset_test: 0123456789abcdefghijklmnopqrstuvwxyz
  batch_size: 192
  weight_decay: 0.0
  warmup_pct: 0.075
  name: transocr
  _target_: strhub.models.transocr.system.TransOCR
  patch_size:
  - 4
  - 4
  enc_embed_dim: 384
  enc_num_heads: 6
  enc_mlp_ratio: 4
  enc_depth: 12
  dec_embed_dim: 384
  dec_num_heads: 12
  dec_mlp_ratio: 4
  dec_depth: 6
  query_type: learn
  standard: true
  lr: 6.0e-06
  perm_num: 6
  perm_forward: true
  perm_mirrored: true
  dropout: 0.1
  decode_ar: true
  refine_iters: 1
  parseq_pretrained: true
  parseq_checkpoint: /home/gaoz/outputs/transocr/finetune-mdr-icdar24-384-20e/2024-03-29_12-11-50/checkpoints/last.ckpt
  encoder_pretrained: false
  encoder_checkpoint: /home/gaoz/pretrained/trans-hybird-mulemb3-prob/checkpoint-19.pth
data:
  _target_: strhub.data.module.SceneTextDataModule
  root_dir: /home/gaoz/datasets/
  train_dir: icdar24
  batch_size: ${model.batch_size}
  img_size: ${model.img_size}
  charset_train: ${model.charset_train}
  charset_test: ${model.charset_test}
  max_label_length: ${model.max_label_length}
  remove_whitespace: true
  normalize_unicode: true
  augment: true
  num_workers: 8
trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  val_check_interval: 1000
  max_epochs: 20
  gradient_clip_val: 20
  accelerator: gpu
  devices: 2
ckpt_path: null
pretrained: null
exp_name: 6e6-finetune-mdr-icdar24-384-20e
