name: transocr
_target_: strhub.models.transocr.system.ClusterSeq

# Data
patch_size: [ 4, 8 ]  # [ height, width ]

# Architecture
enc_embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 12
dec_embed_dim: 384
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 4
query_type: 'learn'

# Training
lr: 7e-4
perm_num: 6
perm_forward: true
perm_mirrored: true
dropout: 0.1

# Decoding mode (test)
decode_ar: true
refine_iters: 1
